/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-04-20 15:46:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Analizi_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("                                                                                                                 \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("                                                                                                          \r\n");
      out.write("                                                                                                                                           \r\n");
      out.write("<div style=\"clear:both;padding-top: 50px;\"></div>                                                                                          \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Алеко Константинов                                                                                                                     \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Bay Ganyo\" class=\"list-group-item\">Бай Ганьо</a>                                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Razni hora, razni ideali\" class=\"list-group-item\">Разни хора, разни идеали</a> \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Razni hora, razni ideali - 1\" class=\"list-group-item\">Разни хора, разни идеали - 1</a>   \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Razni hora, razni ideali - 2\" class=\"list-group-item\">Разни хора, разни идеали - 2</a>   \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Razni hora, razni ideali - 3\" class=\"list-group-item\">Разни хора, разни идеали - 3</a>   \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Razni hora, razni ideali - 4\" class=\"list-group-item\">Разни хора, разни идеали - 4</a>                   \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Атанас Далчев                                                                                                                          \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Bolnitsa\" class=\"list-group-item\">Болница</a>                                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Dyavolsko\" class=\"list-group-item\">Дяволско</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Kamak\" class=\"list-group-item\">Камък</a>                                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Knigite\" class=\"list-group-item\">Книгите</a>                                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Kashtata\" class=\"list-group-item\">Къщата</a>                                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Povest\" class=\"list-group-item\">Повест</a>                                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Prozorets\" class=\"list-group-item\">Прозорец</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Stayata\" class=\"list-group-item\">Стаята</a>                                                        \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Гео Милев                                                                                                                              \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Septemvri\" class=\"list-group-item\">Септември</a>                                                  \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Димитър Димов                                                                                                                          \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Tyutyun\" class=\"list-group-item\">Тютюн</a>                                                          \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Димитър Талев                                                                                                                          \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Zhelezniyat Svetilnik\" class=\"list-group-item\">Железният Светилник</a>                              \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Димчо Дебелянов                                                                                                                        \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Da se zavarnesh...\" class=\"list-group-item\">Да се завърнеш...</a>                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Edin Ubit\" class=\"list-group-item\">Един Убит</a>                                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Mig\" class=\"list-group-item\">Миг</a>                                                              \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Plovdiv\" class=\"list-group-item\">Пловдив</a>                                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Pomnish li, pomnish li\" class=\"list-group-item\">Помниш ли, помниш ли</a>                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Sirotna pesen\" class=\"list-group-item\">Сиротна песен</a>                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Spi Gradat\" class=\"list-group-item\">Спи Градът</a>                                                \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Tiha Pobeda\" class=\"list-group-item\">Тиха Победа</a>                                              \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Cherna pesen\" class=\"list-group-item\">Черна песен</a>                                              \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Елин Пелин                                                                                                                             \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Andreshko\" class=\"list-group-item\">Андрешко</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Vetrenata Melnitsa\" class=\"list-group-item\">Ветрената Мелница</a>                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Geratsite\" class=\"list-group-item\">Гераците</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Zadushnitsa\" class=\"list-group-item\">Задушница</a>                                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Zanemelite kambani\" class=\"list-group-item\">Занемелите камбани</a>                                \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Kosachi\" class=\"list-group-item\">Косачи</a>                                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Mechtateli\" class=\"list-group-item\">Мечтатели</a>                                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Na onya svyat\" class=\"list-group-item\">На оня свят</a>                                              \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Chorba ot grehovete na otets Nikodim\" class=\"list-group-item\">Чорба от греховете на отец Никодим</a>\r\n");
      out.write("                                                                                                                                           \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Елисавета Багряна                                                                                                                      \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Vechnata\" class=\"list-group-item\">Вечната</a>                                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Kukuvitsa\" class=\"list-group-item\">Кукувица</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Potomka\" class=\"list-group-item\">Потомка</a>                                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Stihii\" class=\"list-group-item\">Стихии</a>                                                        \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Иван Вазов                                                                                                                             \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Balgarskiyat ezik\" class=\"list-group-item\">Българският език</a>                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Dyado Yotso gleda\" class=\"list-group-item\">Дядо Йоцо гледа</a>                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Elate ni vizhte\" class=\"list-group-item\">Елате ни вижте</a>                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Kocho\" class=\"list-group-item\">Кочо</a>                                                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Levski\" class=\"list-group-item\">Левски</a>                                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Linee nashto pokolenye\" class=\"list-group-item\">Линее нашто поколенье</a>                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Opalchentsite na Shipka\" class=\"list-group-item\">Опълченците на Шипка</a>                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Otechestvo lyubezno\" class=\"list-group-item\">Отечество любезно</a>                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Paisiy\" class=\"list-group-item\">Паисий</a>                                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Pod igoto\" class=\"list-group-item\">Под игото</a>                                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Pri Rilskiya manastir\" class=\"list-group-item\">При Рилския манастир</a>                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Chichovtsi\" class=\"list-group-item\">Чичовци</a>   \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Epopeya na zabravenite\" class=\"list-group-item\">Епопея на забравените</a>                                                    \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Йордан Йовков                                                                                                                          \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Albena\" class=\"list-group-item\">Албена</a>                                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Drugoselets\" class=\"list-group-item\">Другоселец</a>                                                \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Inzhde\" class=\"list-group-item\">Инжде</a>                                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Pesenta na koleletata\" class=\"list-group-item\">Песента на колелетата</a>                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Posledna radost\" class=\"list-group-item\">Последна радост</a>                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Prez chumavoto\" class=\"list-group-item\">През чумавото</a>                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Serafim\" class=\"list-group-item\">Серафим</a>                                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Shibil\" class=\"list-group-item\">Шибил</a>                                                          \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Никола Вапцаров                                                                                                                        \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Borbata e bezmilostno zhestoka\" class=\"list-group-item\">Борбата е безмилостно жестока</a>          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Vyara\" class=\"list-group-item\">Вяра</a>                                                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Zavod\" class=\"list-group-item\">Завод</a>                                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Istoriya\" class=\"list-group-item\">История</a>                                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Kino\" class=\"list-group-item\">Кино</a>                                                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Pesen za choveka\" class=\"list-group-item\">Песен за човека</a>                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Pismo\" class=\"list-group-item\">Писмо</a>                                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Proshtalno\" class=\"list-group-item\">Прощално</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=San\" class=\"list-group-item\">Сън</a>                                                              \r\n");
      out.write("                                                                                                                                           \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Пейо Яворов                                                                                                                            \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Gradushka\" class=\"list-group-item\">Градушка</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Dve dushi\" class=\"list-group-item\">Две души</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Dve hubavi ochi\" class=\"list-group-item\">Две хубави очи</a>                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Zatochenitsi\" class=\"list-group-item\">Заточеници</a>                                                \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Maska\" class=\"list-group-item\">Маска</a>                                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Pesenta na choveka\" class=\"list-group-item\">Песента на човека</a>                                  \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Senki\" class=\"list-group-item\">Сенки</a>                                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Ston\" class=\"list-group-item\">Стон</a>                                                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Shte badesh v byalo\" class=\"list-group-item\">Ще бъдеш в бяло</a>                                      \r\n");
      out.write("                                                                                                                                           \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Пенчо Славейков                                                                                                                        \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Cis moll\" class=\"list-group-item\">Cis moll</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Ni lah ne dahva nad poleni\" class=\"list-group-item\">Ни лъх не дъхва над полени</a>                \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Ralitsa\" class=\"list-group-item\">Ралица</a>                                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Samoten grob v samoten kat\" class=\"list-group-item\">Самотен гроб в самотен кът</a>                \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Spi ezeroto\" class=\"list-group-item\">Спи езерото</a>                                              \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Христо Ботев                                                                                                                           \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Borba\" class=\"list-group-item\">Борба</a>                                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Do moeto parvo libe\" class=\"list-group-item\">До моето първо либе</a>                              \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Elegiya\" class=\"list-group-item\">Елегия</a>                                                        \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Kam brata si\" class=\"list-group-item\">Към брата си</a>                                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Maytse si\" class=\"list-group-item\">Майце си</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Moyata molitva\" class=\"list-group-item\">Моята молитва</a>                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Na proshtavane 1868g.\" class=\"list-group-item\">На прощаване 1868г.</a>                              \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Obesvaneto na Vasil Levski\" class=\"list-group-item\">Обесването на Васил Левски</a>                \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Hadzhi Dimitar\" class=\"list-group-item\">Хаджи Димитър</a>                                          \r\n");
      out.write("                                                                                                                                           \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("<div class=\"list-group\">                                                                                                                   \r\n");
      out.write("  <a href=\"#\" class=\"list-group-item active\">                                                                                              \r\n");
      out.write("    Христо Смирненски                                                                                                                      \r\n");
      out.write("  </a>                                                                                                                                     \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Da bade den\" class=\"list-group-item\">Да бъде ден</a>                                              \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Zimni vecheri\" class=\"list-group-item\">Зимни вечери</a>                                            \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Yohan\" class=\"list-group-item\">Йохан</a>                                                          \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Niy\" class=\"list-group-item\">Ний</a>                                                              \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Stariya muzikant\" class=\"list-group-item\">Стария музикант</a>                                      \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Tsvetarka\" class=\"list-group-item\">Цветарка</a>                                                    \r\n");
      out.write("  <a href=\"GetAnalizi.jsp?proizvedenie=Yunosha\" class=\"list-group-item\">Юноша</a>                                                          \r\n");
      out.write("</div>                                                                                                                                     \r\n");
      out.write("                                                                                                                                           \r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("                                                                                                                                   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
