/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2014-04-21 21:43:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\r\n");
      out.write("<title>Matura</title>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/bootstrap/css/bootstrap-theme.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<style>\r\n");
      out.write(".list-group{\r\n");
      out.write("//\twidth: 30%;\r\n");
      out.write("margin: 20px;\r\n");
      out.write("}\r\n");
      out.write("pre.tekst{\r\n");
      out.write("\tfont-size: 20px;\r\n");
      out.write("\tfont-family: times new roman;\r\n");
      out.write("\tword-break: normal;\r\n");
      out.write("\twhite-space: pre-wrap;\r\n");
      out.write("\twhite-space: -moz-pre-wrap;\r\n");
      out.write("\twhite-space: -pre-wrap;\r\n");
      out.write("\twhite-space: -o-pre-wrap;\r\n");
      out.write("\tword-wrap: break-word;\r\n");
      out.write("}\r\n");
      out.write("audio {\r\n");
      out.write("  width: 300px;\r\n");
      out.write("  margin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write(".programmers { width: 320px; height: 50px; }\r\n");
      out.write("/* Extra small devices (phones, up to 480px) */\r\n");
      out.write("/* No media query since this is the default in Bootstrap */\r\n");
      out.write("\r\n");
      out.write("/* Small devices (tablets, 768px and up) */\r\n");
      out.write("@media (min-width: 300px) { .programmers { width: 234px; height: 60px; } }\r\n");
      out.write("\r\n");
      out.write("/* Medium devices (desktops, 992px and up) */\r\n");
      out.write("@media (min-width: 600px) { .programmers { width: 320px; height: 50px; } }\r\n");
      out.write("\r\n");
      out.write("/* Large devices (large desktops, 1200px and up) */\r\n");
      out.write("@media (min-width: 800px) { .programmers { width: 728px; height: 90px; margin:0 auto; }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\r\n");
      out.write("  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\r\n");
      out.write("  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\r\n");
      out.write("  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\r\n");
      out.write("\r\n");
      out.write("  ga('create', 'UA-50174770-1', 'cloudbees.net');\r\n");
      out.write("  ga('send', 'pageview');\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"navbar navbar-inverse navbar-fixed-top\" role=\"navigation\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\r\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("            <span class=\"icon-bar\"></span>\r\n");
      out.write("          </button>\r\n");
      out.write("          <a class=\"navbar-brand\" href=\"index.jsp\">Матура</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"navbar-collapse collapse\">\r\n");
      out.write("          <ul class=\"nav navbar-nav\">\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("              <a href=\"\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Литература <b class=\"caret\"></b></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"Proizvedeniq.jsp\">Произведения</a></li>\r\n");
      out.write("                <li><a href=\"Analizi.jsp\">Анализи</a></li>\r\n");
      out.write("                <li><a href=\"AudioBooks.jsp\">Аудио Книги</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"Bulgarski.jsp\">Български</a></li>\r\n");
      out.write("            <li class=\"dropdown\">\r\n");
      out.write("              <a href=\"\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">Какво ще има на матурата по <b class=\"caret\"></b></a>\r\n");
      out.write("              <ul class=\"dropdown-menu\">\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=bel\">Български и Литература</a></li>\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=biologiq\">Биология</a></li>\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=chujd ezik\">Чужд Език</a></li>\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=filosofiq\">Философия</a></li>\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=fizika\">Физика</a></li>\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=geografiq\">География</a></li>\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=istoriq\">История</a></li>\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=matematika\">Математика</a></li>\r\n");
      out.write("                <li><a href=\"MaterialZaMatura.jsp?type=ximiq\">Химия</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div><!--/.nav-collapse -->\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
